### ISSUE TITLE
MPU 9250 轨迹推算~

### ISSUE THREAD

**Issue by fangxu622** [shenshikexmu/IMUCalibration-Gesture#1]
您好~~我在CSDN 博客上看到，写的非常好
本人是惯导 刚入门小兵，想请教一些问题
想利用MPU 9250 做轨迹推算，还没找到相关的轨迹推算程序，做姿态估计的算法也很多，
我使用的是这个 [https://github.com/xioTechnologies/Gait-Tracking-With-x-IMU](https://github.com/xioTechnologies/Gait-Tracking-With-x-IMU) 来做轨迹 推算，直接把数据换成9250 的，但是效果很差
我们也明白单独靠 imu 来做轨迹推算是肯定不行的，但是想请问有没有相关的 通过9250的做轨迹推算的程序，
以及大神对9250 来做轨迹推算有何看法~·

**Comment by shenshikexmu** [comment]
您好，很高兴和你交流。

传感器放脚上的代码我看过，自己没有做过数据跑，最近有空可以采集一下，我觉得不会有太大问题。

只用imu定位我是没有什么思路，也没有查过什么文献。杭州有一家公司之前联系我，说用磁场信息进行定位，我把我的校正代码给他们了就是开源的那个，我的校正和姿态都是假设磁场稳定的，关于大场景的磁场测量我也没有时间自己去采集数据，不知道是否可行，那杭州的公司说对标的美国一家公司，也被谷歌收购了。可能能找到一些文献吧。如果你找到了，可以发给我，可以一起研究研究。

祝好。

发自我的 iPhone

**Comment by Kingshida** [comment]
你可以看看 https://lopsi.weebly.com/downloads.html  这个PDR和航位推算程序，步态识别什么的可以用，或者看一下openshoe，入门的话可以的。

**Comment by shenshikexmu** [comment]
“单独靠IMU推算的产品APP我见过，效果很棒”，名字之类，或者视频demo可以找到吗？求

**Comment by Kingshida** [comment]
我见到的也是封装好的测试SDK，还没有推广，有机会我录一下视频可以看看

**Comment by TrueloveSomeGIRl** [comment]
请问 你博客上的演示app DEMo 有吗  谢谢

**Comment by shenshikexmu** [comment]
https://v.youku.com/v_show/id_XMjUxMDM5Mjk0MA==.html?spm=a2hzp.8244740.0.0

**Comment by fangxu622** [comment]
@shenshikexmu 单独靠IMU推算的产品，这需要很好的IMU把·~·

**Comment by shenshikexmu** [comment]
单imu很难，个人觉得

**Comment by fangxu622** [comment]
@shenshikexmu  有这样的递推开源方案没~~

**Comment by shenshikexmu** [comment]
我也想知道，可能还是要加视觉之类

**Comment by shenshikexmu** [comment]
@fangxu622 刚知道同济大学的刘儿兀教授的DWELT，这个是做室内定位，论文还没看。目前知道的就这些。

**Comment by fangxu622** [comment]
> @fangxu622 刚知道同济大学的刘儿兀教授的DWELT，这个是做室内定位，论文还没看。目前知道的就这些。

恩恩``好的,多谢
