### ISSUE TITLE
磁力计校正部分有参考论文或者博客吗

### ISSUE THREAD

**Issue by yanyilin000** [shenshikexmu/IMUCalibration-Gesture#10]
您好，请问磁力计部分有参考的论文或者博客，任何详细一些的理论来源都可以，谢谢！！

**Comment by shenshikexmu** [comment]
我自己想的，博客不想写了，和加速度角速度校正一个原理啊，就是逆过程而已。

**Comment by yanyilin000** [comment]
感谢您的回复，还有问题就是您的原始数据单位都是多少？如果我的坐标不是东北天，用您的代码会有什么影响吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 张欣 <notifications@github.com>
发送时间: 2019年8月15日 15:36
收件人: shenshikexmu/IMUCalibration-Gesture <IMUCalibration-Gesture@noreply.github.com>
抄送: yanyilin000 <743783201@qq.com>, Author <author@noreply.github.com>
主题: 回复：[shenshikexmu/IMUCalibration-Gesture] 磁力计校正部分有参考论文或者博客吗 (#10)




我自己想的，博客不想写了，和加速度角速度校正一个原理啊，就是逆过程而已。

**Comment by shenshikexmu** [comment]
原始数据2048对应1G。只有Vm这个参数是在东北天坐标系。其他都是IMU坐标系。

**Comment by yanyilin000** [comment]
我的意思是比如您的加速度某轴的数据值大小为196，是对应多少m/s^2？或者多少g？因为我看您数据值都很大



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 张欣 <notifications@github.com>
发送时间: 2019年8月16日 11:48
收件人: shenshikexmu/IMUCalibration-Gesture <IMUCalibration-Gesture@noreply.github.com>
抄送: yanyilin000 <743783201@qq.com>, Author <author@noreply.github.com>
主题: 回复：[shenshikexmu/IMUCalibration-Gesture] 磁力计校正部分有参考论文或者博客吗 (#10)




原始数据2048对应1G。只有Vm这个参数是在东北天坐标系。其他都是IMU坐标系。

**Comment by shenshikexmu** [comment]
加速度2048对应1g，9.8m/s^2，可以在mpu9250文档里找到

**Comment by yanyilin000** [comment]
好的好的，谢谢您



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 张欣 <notifications@github.com>
发送时间: 2019年8月16日 12:10
收件人: shenshikexmu/IMUCalibration-Gesture <IMUCalibration-Gesture@noreply.github.com>
抄送: yanyilin000 <743783201@qq.com>, Author <author@noreply.github.com>
主题: 回复：[shenshikexmu/IMUCalibration-Gesture] 磁力计校正部分有参考论文或者博客吗 (#10)




加速度2048对应1g，9.8m/s^2，可以在mpu9250文档里找到

**Comment by yanyilin000** [comment]
张老师不好意思再打扰您一下，刚刚在读您的代码，在剪切数据的时候也就是函数FindFixData里的rotation这个数组是什么意思？里面的30代表什么，是您上面设置的阈值30的意思吗？我附上了图片



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 张欣 <notifications@github.com>
发送时间: 2019年8月16日 12:10
收件人: shenshikexmu/IMUCalibration-Gesture <IMUCalibration-Gesture@noreply.github.com>
抄送: yanyilin000 <743783201@qq.com>, Author <author@noreply.github.com>
主题: 回复：[shenshikexmu/IMUCalibration-Gesture] 磁力计校正部分有参考论文或者博客吗 (#10)




加速度2048对应1g，9.8m/s^2，可以在mpu9250文档里找到

**Comment by shenshikexmu** [comment]
ICRA2014校正那篇论文你要读一下 A Robust and Easy to implement method for imu calibration without External Equipments

FindFixData这个函数我没按论文的方法写（论文的算法我自己写过，感觉太耗时没用），实现的功能是一样的。

**Comment by yanyilin000** [comment]
嗯嗯，我今天把您的博客和代码以及论文都搞懂了差不多了，十分感谢您的回复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 张欣 <notifications@github.com>
发送时间: 2019年8月17日 16:12
收件人: shenshikexmu/IMUCalibration-Gesture <IMUCalibration-Gesture@noreply.github.com>
抄送: yanyilin000 <743783201@qq.com>, Author <author@noreply.github.com>
主题: 回复：[shenshikexmu/IMUCalibration-Gesture] 磁力计校正部分有参考论文或者博客吗 (#10)
