### ISSUE TITLE
mohony filter 和其他几个filter都设置了Q(1) < 0 则Q= -Q 目的是什么 

### ISSUE THREAD

**Issue by VinchinYang** [shenshikexmu/IMUCalibration-Gesture#12]
mohony filter 和其他几个filter都设置了Q(1) < 0 则Q= -Q 目的是什么 ，这样做会导致最后得到的结果曲线不连续或者说跳边的

**Comment by shenshikexmu** [comment]
为了好看吧，比较算法方便，有的是Q，有的是-Q，滤波后的四元数不好分清好坏。还是统一q1大于0好看一些。

**Comment by VinchinYang** [comment]
感谢抽空回答。单位四元数可以表达任意旋转的，而且没有奇异性的。 
1.不同算法滤波后，真值解应当是唯一的。不太理解为什么 -Q 不好分清好坏
2.下一次滤波是在上一次滤波结果上继续的，这样难道不会影响后面的解吗

再次感谢指点

**Comment by shenshikexmu** [comment]
因为四元数比如
[0.122965663988648	0.310034049395613	-0.942381176011782	-0.0260010152463525]
与
[-0.122965663988648   -0.310034049395613	  0.942381176011782	  0.0260010152463525]
表示相同一个姿态，我是想比较不同算法，所以在滤波后强行把四元数第一项设置为大于零。
你可以试一下直接用滤波后的四元数，线可能是连续的，但几个算法的结果有可能出现沿0轴对称。

**Comment by VinchinYang** [comment]
谢谢
