### ISSUE TITLE
Question about threshold

### ISSUE THREAD

**Issue by ColleenKuang** [shenshikexmu/IMUCalibration-Gesture#15]
I read the paper and I wonder why u determine threshold directly? and why the threshold is 30?
Looking forward to your reply

**Comment by shenshikexmu** [comment]
中国人吧，直接用中文回答了，算法是我复现ICRA2014这篇论文的，threshold是经验值，论文中是用方差来设置的，我matlab上窗口计算方差，计算量太大，而且还设置n乘以方差值滤加速度数据，计算好几组加速度参数，我也觉得没必要，计算方差的对应算法我写过，但开源代码的时候，认为这不是IMU标定本质的东西，就没有放进去，自己写了个简便的，就是你看到的这个。主要是觉得不美吧，我个人的一点偏执。
