### ISSUE TITLE
数据模型

### ISSUE THREAD

**Issue by guofengw** [shenshikexmu/IMUCalibration-Gesture#2]
您好，我在您的博客中看到IMU标定相关的内容，有一点不明白，为什么您的模型是raw数据+bias呢（如下所示），这里的raw数据是真实数据还是IMU采的数据呢？谢谢。
calacc=Ta∗Ka∗(rawacc+Ba)

**Comment by shenshikexmu** [comment]
raw_acc是imu采集数据，cal_acc是校正后数据，它们都会包含高斯噪声，这个是校正算法去除不掉的。
