### ISSUE TITLE
如何得到 caldata.mat

### ISSUE THREAD

**Issue by AaronZhu2018** [shenshikexmu/IMUCalibration-Gesture#3]
您好我有一個疑問，畢竟每一個mpu9250都不一樣，要如何得到caldata.mat的數據?
需要做的步驟是?

**Comment by Arsenezhu** [comment]
依照內文是 time accelerometer  gyroscope   magnetometer
若是即時的輸入這些數據,就可以即時的看到姿態嗎?
需要將校正數據寫入mpu9250的register中嗎?
謝謝您的回覆

**Comment by shenshikexmu** [comment]
数据的采集： 我的方法是把传感器粘在篮球上，把篮球放到透明胶带的圆环上，通过转动篮球，使传感器呈现不同姿态，采集数据。
姿态融合上： 在哪一步做校正（乘以校正参数），我个人觉得都不是问题。看你的代码习惯了。

**Comment by Arsenezhu** [comment]
謝謝您的回覆，我在多看看研究研究

**Comment by shenshikexmu** [comment]
我邮件上问你问题还没有回呢？

**Comment by LLlkaiwen** [comment]
请问您采集的caldata是mpu9250的原始数据吗，mpu9250加速度计和磁力计的坐标系不一致，有没有做坐标系统一的处理呀，我想用caldata的数据做校正和滤波，所以想了解一下，谢谢

**Comment by shenshikexmu** [comment]
采集的是原始数据，坐标系不一致csdn博客上说明了。代码上设置好直接用

**Comment by fangxu622** [comment]
cal_data 都没有小数 全是整数数据
加速度计数据这么大？？
![image](https://user-images.githubusercontent.com/16681534/62723255-cbb8bb00-ba42-11e9-903b-c3e13514a646.png)

**Comment by shenshikexmu** [comment]
数据是原始数据

**Comment by fangxu622** [comment]
> 数据是原始数据

这是我的原始数据


![image](https://user-images.githubusercontent.com/16681534/62846268-575f6f80-bd01-11e9-9e11-e635555322cf.png)

原始数据显示

原始数据使用您的方法进行校正，感觉出来的数据完全不对。不知道是哪里出错了
经过校正的数据

磁力计
![image](https://user-images.githubusercontent.com/16681534/62846360-419e7a00-bd02-11e9-85dd-f2bfa0a9de60.png)

**Comment by shenshikexmu** [comment]
可能不是数据问题，可能是你用算法的问题吧，我的博客你再好好读读吧。

**Comment by jamesjian007** [comment]
我看了你的博客， 我还是没搞懂 这个CALDATA 文件 是怎么得来， 是用arduino 加MPU9250 吗？

**Comment by shenshikexmu** [comment]
> 我看了你的博客， 我还是没搞懂 这个CALDATA

imu数据通过蓝牙传手机上来的。
