### ISSUE TITLE
可以讲一下FindMixData的算法吗

### ISSUE THREAD

**Issue by yanyilin000** [shenshikexmu/IMUCalibration-Gesture#4]
新手小白，把博主推荐的都论文看了，现在啃代码，但是在摘数据这部分就卡住了。。。博主在ISDN上说没用论文里的方差法，而是用了另外的方法，这个FindMixData具体的算法有详细的解释吗，代码里很多细节看的不是很明白。。。也许我的问题很弱，但是还是希望博主能给我解答，谢谢

**Comment by shenshikexmu** [comment]
一把剪刀，把数据裁剪到需要的
