### ISSUE TITLE
加速度计与陀螺仪标定误差

### ISSUE THREAD

**Issue by mallxy** [shenshikexmu/IMUCalibration-Gesture#6]
您好，我尝试将数据带入对比测量值和校正值误差大小，发现加速度值和角速度值差距在数量级10^4和10^3，想请问是为什么？谢谢！在您原程序基础上加的程序如下：
for i=1:n
 cal_acc(1:3,i)=Ta*Ka*(cal_data(i,2:4)'+Ba);
 cal_gyro(1:3,i)=Tg*Kg*(cal_data(i,5:7)'+Bg);
end

cal_acc_n=cal_acc';
cal_gyro_n=cal_gyro';
err_acc=cal_acc_n(:,1:3)-cal_data(:,2:4);
err_gyro=cal_gyro_n(:,1:3)-cal_data(:,5:7);
subplot(2,1,1);plot(1:n,err_acc);title('acc');
subplot(2,1,2);plot(1:n,err_gyro);title('gyro');

**Comment by shenshikexmu** [comment]
看了你的问题，我想了半天没有搞懂，不知道为什么要做这样的比较。我猜你可能不是很清楚“校正（calibration）”是在做什么。推荐你看论文《A Robust and Easy to implement method for imu calibration without External Equipments》，这篇博客也可以，https://www.cnblogs.com/buxiaoyi/p/7541974.html

**Comment by mallxy** [comment]
> 看了你的问题，我想了半天没有搞懂，不知道为什么要做这样的比较。我猜你可能不是很清楚“校正（calibration）”是在做什么。推荐你看论文《A Robust and Easy to implement method for imu calibration without External Equipments》，这篇博客也可以，https://www.cnblogs.com/buxiaoyi/p/7541974.html

好的，谢谢

**Comment by mallxy** [comment]
您好，我仔细看了下您提到的文献，有些问题还是不太懂。
1.原始测量数据和校正后的数据应该具有相关性，至少图像形状上应该相近吧（我之前加的那个程序就是看二者是不是差别很大）？我用您这的程序进行校正之后，再算传感器俯仰角，发现和实际不符，而不经过校正，直接由原始数据算俯仰角，结果反倒相近；
2.校正之后的Tg，Ta，ka，kg，Ba，Bg等值是在之后的使用中能直接拿来用的吧？这样的话，照理说同样一个的传感器，标定得到的这些值应该是差不多的吧可是我按照文献说的方法进行标定，试了3次，3次的Tg，Ta，Ba，Bg值都不太一样，请问是为什么？
谢谢

**Comment by shenshikexmu** [comment]
你确定你校正成功了，我的算法后面有个姿态呈现，你的数据跑出来的几个姿态呈现基本一样吗？还有你的数据采样率是多少，1秒钟100帧吗？

**Comment by mallxy** [comment]
刚试了下，姿态呈现基本一样。采样率因为传感器原因，会变动。将校正后的值cal_acc=Ta*Ka*(raw_acc+Ba)代替raw_acc带入我自己的算法里算俯仰角，如前所述，cal_acc的与实际不符，而raw_acc的与实际较符合。不太清楚是怎么回事

采集的数据是类似这样的：
1726.208	0	0.002	0.9971	0	0	0	-286.5	-1.5	-193.5
1726.208	-0.001	0.0024	1.0015	0	0	0	-285	-3	-195
1726.264	-0.002	0.0029	1.001	0	0	0	-283.5	-4.5	-193.5
1726.266	-0.0005	0.0034	0.999	0	0	0	-283.5	-3	-192
1726.266	0.0005	0.002	0.998	0	0	0	-286.5	0	-192
1726.266	-0.0029	0.001	0.9985	0	0	0	-286.5	0	-195
1726.267	-0.001	0.0015	1.0005	0	0	0	-288	-3	-196.5
1726.267	0	0.002	0.9985	0	0	0	-288	-3	-193.5
1726.268	-0.002	0.0034	1.0005	0	0	0	-286.5	-3	-193.55
1725.655	-0.0005	0.0044	1.0024	0	0	-0.061	-285	-3	-195
1725.655	-0.002	0.0034	1	0	0	-0.061	-286.5	-1.5	-196.5
1725.655	-0.0005	0.0029	0.9995	0	0	0	-288	0	-196.5

**Comment by shenshikexmu** [comment]
我没有你的传感器，这盲人摸象，一直做排除法有点难啊。看你的数据，Ka应该是个近似9.8*eye(3)的矩阵。我猜你的数据并没有像论文一样采集，也不知道姿态呈现基本一样到什么程度，或者你的传感器不是mpu9250（mpu9250加速度坐标系与磁力计坐标系不同，见https://blog.csdn.net/shenshikexmu/article/details/80013444），其它可能就帮不到你了。

**Comment by mallxy** [comment]
好的，谢谢，我再自己研究下
