### ISSUE TITLE
关于磁力计的坐标变换问题

### ISSUE THREAD

**Issue by Ryan2F** [shenshikexmu/IMUCalibration-Gesture#7]
您好，请问用您的代码做完校正后，磁力计的输出也就是在加速度计坐标系下的投影了吧？谢谢！

**Comment by shenshikexmu** [comment]
对。加速度、角速度、磁力计同一个坐标系了

**Comment by Ryan2F** [comment]
非常感谢！

**Comment by Ryan2F** [comment]
由于mpu9250的陀螺敏感不到地球自转角速度，所以考虑用加表和磁力计输出做双矢量定姿来确定初始姿态，不知这样是否可行？您有什么建议？

**Comment by shenshikexmu** [comment]
代码里不是有吗，就是怎么做的

**Comment by Ryan2F** [comment]
您好，还是刚刚的问题。我看了下您的代码，代码里在用加表和磁力计输出做双矢量定姿来确定初始姿态时的算法和用陀螺和加表是一样的。但磁感应强度在地理坐标系下并不是指向真北的。不知您是否考虑了地磁偏角的问题，是否做了补偿？

**Comment by shenshikexmu** [comment]
有啊，Vm就是，再不认真看代码，问我已经解决好的问题，我就要收咨询费了!
问点我没决绝的问题吧。

**Comment by Ryan2F** [comment]
谢谢回复！刚接触惯导，在学习。

**Comment by Ryan2F** [comment]
使用您的代码，校正后看姿态，在刚开始静止状态时，gyro in RK4显示的姿态就一直在转，最后一帧的姿态也只有这个和其他的姿态对不上，请问这是什么原因呢？再次请教，感谢！

**Comment by shenshikexmu** [comment]
看了下代码，我觉得应该不会出现你的问题，only gyro 和 gyro in RK4共用的一套数据，应该差不多的，我想不明白为什么会出现你描述的问题，帮不上你了。
