### ISSUE TITLE
参数设置的问题

### ISSUE THREAD

**Issue by 1NoWei** [shenshikexmu/IMUCalibration-Gesture#8]
您好，我想问一下，陀螺加速度计和磁力计的校正代码里都有个参数a0，请问这个参数值给定的依据是什么？谢谢。

**Comment by shenshikexmu** [comment]
理论上什么值都可以，loss function是个绝对凸函数，当然离真实值越近越好

**Comment by rubbish-wei** [comment]
好的，感谢。我还想问一下您的代码对传感器量程选择有要求吗？您选的是什么范围的量程？谢谢。

**Comment by shenshikexmu** [comment]
随便
