### ISSUE TITLE
姿态估计精度

### ISSUE THREAD

**Issue by huangxinCAS** [shenshikexmu/IMUCalibration-Gesture#9]
您好，我关注您的博客和代码有一段时间了，也自己采集数据标定了mpu9250。有几个问题想请教一下您~
（1）这是我用加速度计和陀螺仪融合得到的姿态数据，dmp算是硬件自己解算的，不知道为什么z轴的误差这么大？融合磁力计能解决这个问题吗？（图片传不上去，就是z轴比较漂。。）
（2）该如何衡量姿态解算的精度？？？

**Comment by shenshikexmu** [comment]
（1）我不知道你说的Z轴是什么的Z轴，两个不平行的向量可以确定一个物体的姿态，在IMU里，重力的向量和磁力向量，如果没有磁力向量，IMU相同的重力向量下，磁力向量可以画一个圈，至于磁力向量在这个圈的哪个点上只能猜了，不知是不是这个猜的结果让你的Z轴的误差很大。
（2）这个标准我不知道，也想知道。我猜取决你的应用场景了吧。传感器都是有噪音的，怎么让噪音影响最小，校正可以减少噪音，滤波也可以减少噪音。

**Comment by huangxinCAS** [comment]
1. 您能给一下您的邮箱吗？我把结果的图片发给您？
2. 我也是按您的程序进行了滤波，

**Comment by huangxinCAS** [comment]
您给给一下您的邮箱吗？还是上传不了图片。。

**Comment by shenshikexmu** [comment]
shenshikexmu@163.com
